# ==========================================
# SISTEMA DE ESTACIONAMENTO
# ==========================================

# Nome da aplicação
spring.application.name=SistemaEstacionamento

# Porta onde a aplicação será executada
server.port=8080